export const COLORS = {
  primary: "#E53935",
  primaryLight: "#FFEBEE",
  secondary: "#1565C0",
  success: "#2E7D32",
  warning: "#F57F17",
  danger: "#B71C1C",
  gray: "#757575",
  grayLight: "#F5F5F5",
  grayBorder: "#E0E0E0",
  white: "#FFFFFF",
  black: "#212121",
  text: "#333333",
  textLight: "#757575",
};

export const CATEGORIES = [
  { value: "rescue", label: "🆘 Cần cứu hộ người", color: "#E53935" },
  { value: "supplies", label: "📦 Cần nhu yếu phẩm", color: "#F57F17" },
  { value: "vehicle_rescue", label: "🚗 Cần cứu hộ xe", color: "#1565C0" },
  { value: "other", label: "❓ Khác", color: "#757575" },
];

export const STATUS_CONFIG = {
  new: { label: "Mới tạo", color: "#1565C0", bg: "#E3F2FD", icon: "🆕" },
  pending_verification: {
    label: "Đang xét duyệt",
    color: "#F57F17",
    bg: "#FFF8E1",
    icon: "⏳",
  },
  verified: {
    label: "Đã xác minh",
    color: "#7B1FA2",
    bg: "#F3E5F5",
    icon: "✅",
  },
  on_mission: {
    label: "Đang cứu hộ",
    color: "#E53935",
    bg: "#FFEBEE",
    icon: "🚨",
  },
  completed: {
    label: "Hoàn thành",
    color: "#2E7D32",
    bg: "#E8F5E9",
    icon: "✔️",
  },
  rejected: { label: "Từ chối", color: "#757575", bg: "#F5F5F5", icon: "❌" },
};

export const PRIORITIES = [
  { value: "urgent", label: "🔴 Khẩn cấp", color: "#B71C1C" },
  { value: "high", label: "🟠 Cao", color: "#E53935" },
  { value: "medium", label: "🟡 Trung bình", color: "#F57F17" },
  { value: "low", label: "🟢 Thấp", color: "#2E7D32" },
];

export const PROVINCES = [
  "Hà Nội",
  "TP. Hồ Chí Minh",
  "Đà Nẵng",
  "Cần Thơ",
  "Hải Phòng",
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Dương",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cao Bằng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Tĩnh",
  "Hải Dương",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
];
